[workspace]
members = [
  "crates/app_engine",
  "crates/core",
  "crates/network",
  "crates/persistance",
  "crates/client_gui",
]
resolver = "2"
default-members = ["crates/client_gui"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unsafe_code = "forbid"
