[package]
name = "app_engine"
version.workspace = true
edition.workspace = true

[dependencies]
core = { path = "../core/" }
network = { path = "../network/" }
flume = "0.12.0"
tokio = "1.49.0"
qr2term = "0.3.3"

[lints]
workspace = true
