[package]
name = "client_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
app_engine = { path = "../app_engine/" }
core = { path = "../core/" }
derive-new = "0.7.0"
flume = "0.12.0"
gpui = "0.2.2"
gpui-component = "0.5.0"
tokio = "1.49.0"
