[package]
name = "network"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = "1.49.0"
wacore = "0.2.0"
whatsapp-rust = "0.2.0"
whatsapp-rust-tokio-transport = "0.2.0"
whatsapp-rust-ureq-http-client = "0.2.0"

[lints]
workspace = true
